### ISSUE TITLE
View on Github is redirecting to old github repo

### ISSUE THREAD

**Issue by shawn0x1** [FinalGravityBrewing/website#1]
probably a link in the index.html code.  Will check out tomorrow, if anybody has any free time to look into this feel free to tackle the problem.

**Comment by rlmcpherson** [comment]
I removed that link and the download source links from the header. They're more relevant to software projects and I think the site looks cleaner without them.

**Comment by rlmcpherson** [comment]
There's still a link to the github account in the footer, and I updated that to point to the group account.
